version: "3.4"
services:
  db:
    image: "postgres"
    container_name: db
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=root
    volumes:
        - db_data:/var/lib/postgresql/data
  fastapi:
    container_name: demoApp
    build: .
    ports: 
        - "8000:8000"
    depends_on:
        - db
        - kafka
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
  zookeeper:
    container_name: zookeeper
    image: "zookeeper"
    ports:
        - "2181:2181"
  kafka:
    container_name: kafka
    image: "confluentinc/cp-kafka"
    ports:
        - "9092:9092"
    environment:
        - KAFKA_ZOOKEEPER_CONNECT=192.168.1.26:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.26:9092
        - KAFKA_OFSETS_TOPIC_REPLICATION_FACTOR=1
  grafana:
    container_name: grafana
    image: "grafana/grafana"
    ports:
        - "3000:3000"
volumes:
    db_data: